x-status: &status
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "3"

x-env: &env-file
  env_file:
    - .env


services:
  db:
    image: postgres:alpine3.18
    container_name: db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    <<:
      - *status
      - *env-file
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9090:8080"